### PR TITLE
Migrate on `typelevel` organization

### PR DESCRIPTION
**Pull request by danicheg**
This PR is mainly a proposal. Perhaps, this will also require changing the secrets for publishing.
What do you folks think about it? @cquiroz @ChristopherDavenport @rossabaker

### CODE REVIEW

**Review by ChristopherDavenport — APPROVED** [review]
I certainly don't mind. That was my intention 😄

**Comment by ChristopherDavenport** [comment]
I think I can publish to typelevel already. And if not then I should go ask for that regardless. So I don't think creds should need to change.

**Review by rossabaker — APPROVED** [review]

**Comment by cquiroz** [comment]
Hi sorry, I thought it was mostly a question for Chris, but sure this sounds fine. In case publication fails I have credentials to publish under typelevel

Changing version number should be ok,
I think scala steward can handle the org change but I'm not sure if the version number has to keep up with the old org

**Review by cquiroz — APPROVED** [review]
LGTM

**Review by lukoyanov — APPROVED** [review]
LGTM.

**Comment by cquiroz** [comment]
It seems we could merge this and attempt a M1 release

**Comment by cquiroz** [comment]
It worked just fine
https://repo1.maven.org/maven2/org/typelevel/cats-time_3/0.4.1-M1/

**Comment by cquiroz** [comment]
It seems adding a migration to scala-steward would be possible

**Comment by danicheg** [comment]
Great!

**Comment by cquiroz** [comment]
https://github.com/scala-steward-org/scala-steward/pull/2354

**Comment by cquiroz** [comment]
I'll release version 0.5.0 and setup the migration on scala-steward

**Pull request merged**
